version: '3.9'
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "9123:9123"
  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "9124:80"
    depends_on:
      - api